name: Deploy DeroGold

on:
  push:
    tags:
      - "*"

  workflow_dispatch:
    inputs:
      draft_release:
        description: 'Create a draft release'
        default: false
        required: false
        type: boolean

defaults:
  run:
    shell: pwsh

jobs:
  env:
    name: Get DeroGold Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_output_version.outputs.version }}
      is_latest_version: ${{ steps.is_latest_version.outputs.is_latest_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: get_output_version
        run: |
          Get-Content "CMakeLists.txt" | Select-String 'project\(DeroGold VERSION ([0-9.]+) ' | ForEach-Object { "version=" + $_.Matches[0].Groups[1].Value } >> "$env:GITHUB_OUTPUT"

      - id: is_latest_version
        run: |
          echo is_latest_version=$($(git describe --tags --abbrev=0) -eq "${{ steps.get_output_version.outputs.version }}") >> "$env:GITHUB_OUTPUT"

  build_derogold:
    name: ${{ matrix.build_preset }}
    runs-on: ${{ matrix.os }}
    needs: env

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macos-12]
        arch: [x64, arm64]
        compiler: [msvc, gcc, clang]

        exclude:
          - os: windows-latest
            arch: arm64
          - os: macos-12
            arch: arm64
          - os: ubuntu-20.04
            compiler: msvc
          - os: ubuntu-20.04
            arch: arm64
            compiler: clang
          - os: macos-12
            compiler: msvc
          - os: macos-12
            compiler: gcc

        include:
          - os: windows-latest
            arch: x64
            compiler: msvc
            install: ""
            configure_preset: windows-x64-msvc-package
            build_preset: windows-x64-msvc-package

          - os: windows-latest
            arch: x64
            compiler: gcc
            install: ""
            msys2_environment: MINGW64
            msys2_install: >-
              mingw-w64-x86_64-toolchain
              mingw-w64-x86_64-cmake
              mingw-w64-x86_64-ninja
            configure_preset: windows-x64-mingw-gcc-package
            build_preset: windows-x64-mingw-gcc-package

          - os: windows-latest
            arch: x64
            compiler: clang
            install: ""
            msys2_environment: CLANG64
            msys2_install: >-
              mingw-w64-clang-x86_64-toolchain
              mingw-w64-clang-x86_64-cmake
              mingw-w64-clang-x86_64-ninja
            configure_preset: windows-x64-mingw-clang-package
            build_preset: windows-x64-mingw-clang-package

          - os: ubuntu-20.04
            arch: x64
            compiler: gcc
            install: >-
              cmake
              ninja-build
              build-essential
              curl
              zip
              unzip
              tar
              pkg-config
            configure_preset: linux-x64-gcc-package
            build_preset: linux-x64-gcc-package

          - os: ubuntu-20.04
            arch: x64
            compiler: clang
            install: >-
              cmake
              ninja-build
              clang
              curl
              zip
              unzip
              tar
              pkg-config
            configure_preset: linux-x64-clang-package
            build_preset: linux-x64-clang-package

          - os: ubuntu-20.04
            arch: arm64
            compiler: gcc
            install: >-
              cmake
              ninja-build
              crossbuild-essential-arm64
              curl
              zip
              unzip
              tar
              pkg-config
            configure_preset: linux-arm64-gcc-cross-package
            build_preset: linux-arm64-gcc-cross-package

          - os: macos-12
            arch: x64
            compiler: clang
            install: >-
              cmake
              ninja
              llvm
              pkg-config
            configure_preset: osx-x64-clang-package
            build_preset: osx-x64-clang-package

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Install Program / Dependencies
        run: |
          if ("${{ runner.os }}" -eq "Windows")
          {
            if (![string]::IsNullOrWhiteSpace("${{ matrix.install }}"))
            {
              choco install -y ${{ matrix.install }}
            }
          }
          elseif ("${{ runner.os }}" -eq "Linux")
          {
            if (![string]::IsNullOrWhiteSpace("${{ matrix.install }}"))
            {
              sudo apt-get update -y
              sudo apt-get install -y ${{ matrix.install }}
            }
          }
          elseif ("${{ runner.os }}" -eq "macOS")
          {
            if (![string]::IsNullOrWhiteSpace("${{ matrix.install }}"))
            {
              brew update
              brew install ${{ matrix.install }}
            }
          }

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows' && matrix.compiler != 'msvc'
        with:
          update: true
          install: ${{ matrix.msys2_install }}
          msystem: ${{ matrix.msys2_environment }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Build DeroGold (MSVC)
        if: runner.os == 'Windows' && matrix.compiler == 'msvc'
        working-directory: ${{ github.workspace }}
        shell: cmd
        run: |
          cmake --preset ${{ matrix.configure_preset }}
          cmake --build --preset ${{ matrix.build_preset }}

      - name: Build DeroGold (MSYS2)
        if: runner.os == 'Windows' && matrix.compiler != 'msvc'
        working-directory: ${{ github.workspace }}
        shell: msys2 {0}
        run: |
          cmake --preset ${{ matrix.configure_preset }}
          cmake --build --preset ${{ matrix.build_preset }}

      - name: Build DeroGold (GCC/CLANG)
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}
        run: |
          cmake --preset ${{ matrix.configure_preset }}
          cmake --build --preset ${{ matrix.build_preset }}

      - name: Collect Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-vcpkg-build-logs
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
          if-no-files-found: ignore

      - name: Upload Package
        uses: actions/upload-artifact@v4
        if: success() 
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-build
          path: |
            ${{ github.workspace }}/build/Packaging/*.zip
            ${{ github.workspace }}/build/Packaging/*.tar.gz
            ${{ github.workspace }}/build/Packaging/*.deb
          if-no-files-found: ignore

  deploy_derogold:
    name: Deploy DeroGold
    runs-on: ubuntu-latest
    needs: [env, build_derogold]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create artifact directory
        run: |
          New-Item 'build' -ItemType 'Directory' -Force

      - name: Download DeroGold artifact
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true

      - name: Deploy DeroGold
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/RELEASE_TEMPLATE.md
          name: v${{ needs.env.outputs.version }}
          tag_name: ${{ needs.env.outputs.version }}
          draft: ${{ github.event.inputs.draft_release }}
          files: |
            ${{ github.workspace }}/build/*.zip
            ${{ github.workspace }}/build/*.tar.gz
            ${{ github.workspace }}/build/*.deb

  docker_build_derogold:
    name: Deploy DeroGold Docker (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    needs: env

    env:
      DOCKER_HUB_REPOSITORY: jianmingyong/derogold

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: tags
        run: |
          $output = @()
          $output += "${{ env.DOCKER_HUB_REPOSITORY }}:${{ needs.env.outputs.version }}-${{ matrix.compiler }}"

          if ("${{ matrix.compiler }}" -eq "gcc")
          {
            $output += "${{ env.DOCKER_HUB_REPOSITORY }}:${{ needs.env.outputs.version }}"
          }

          if ("${{ github.event.inputs.draft_release }}" -eq "false" -And "${{ needs.env.outputs.is_latest_version }}" -eq "true")
          {
            $output += "${{ env.DOCKER_HUB_REPOSITORY }}:latest-${{ matrix.compiler }}"

            if ("${{ matrix.compiler }}" -eq "gcc")
            {
              $output += "${{ env.DOCKER_HUB_REPOSITORY }}:latest"
            }
          }

          echo tags=$([string]::Join(",", $output)) >> "$env:GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          target: release_${{ matrix.compiler }}
          tags: ${{ steps.tags.outputs.tags }}
          push: true
          
